Repository HealEat/Backend, pull requests merged in 2025-02, with the labels that each got.

#128 [FEAT] Caffeine 설정 및 적용, SearchResult, 서비스 로직 간소화
  build.gradle
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/java/healeat/server/HealEatServerApplication.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/domain/search/SearchResult.java
  src/main/java/healeat/server/repository/SearchResultRepository.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/SearchController.java
Labels: :sparkles: feature

#131 [FEAT] #118-term, MemberTerm
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/TermHandler.java
  src/main/java/healeat/server/domain/Term.java
  src/main/java/healeat/server/repository/MemberTermRepository.java
  src/main/java/healeat/server/repository/TermRepository.java
  src/main/java/healeat/server/service/TermService.java
  src/main/java/healeat/server/web/controller/TermController.java
  src/main/java/healeat/server/web/dto/TermResponse.java
  src/main/java/healeat/server/web/dto/TermsAgreeRequest.java
  src/main/resources/data.sql
Labels: :sparkles: feature

#145 홈 가게 추천 구현
  src/main/generated/healeat/server/domain/QDisease.java
  src/main/generated/healeat/server/domain/QFoodCategory.java
  src/main/generated/healeat/server/domain/QFoodFeature.java
  src/main/generated/healeat/server/domain/QHealthPlan.java
  src/main/generated/healeat/server/domain/QHealthPlanImage.java
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/generated/healeat/server/domain/QReviewImage.java
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/generated/healeat/server/domain/common/QBaseEntity.java
  src/main/generated/healeat/server/domain/mapping/QBookmark.java
  src/main/generated/healeat/server/domain/mapping/QFeatCategoryMap.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/generated/healeat/server/domain/mapping/QMemberTerm.java
  src/main/generated/healeat/server/domain/mapping/QRecentSearch.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/search/SearchResult.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/SearchFeatureService.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
  src/main/resources/application.yml.template
Labels: :sparkles: feature

#150 #148-MyPage 나의 건강 정보 조회 api
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/dto/HealInfoResponseDto.java
Labels: :sparkles: feature

#153 #146 [FEAT] 가게 이미지 조회 구현 (Daum 이미지 API 활용)
  src/main/generated/healeat/server/domain/QDisease.java
  src/main/generated/healeat/server/domain/QFoodCategory.java
  src/main/generated/healeat/server/domain/QFoodFeature.java
  src/main/generated/healeat/server/domain/QHealthPlan.java
  src/main/generated/healeat/server/domain/QHealthPlanImage.java
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/generated/healeat/server/domain/QReviewImage.java
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/generated/healeat/server/domain/common/QBaseEntity.java
  src/main/generated/healeat/server/domain/mapping/QBookmark.java
  src/main/generated/healeat/server/domain/mapping/QFeatCategoryMap.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/generated/healeat/server/domain/mapping/QMemberTerm.java
  src/main/generated/healeat/server/domain/mapping/QRecentSearch.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/DaumImageService.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
  src/main/java/healeat/server/web/dto/api_response/DaumImageResponseDto.java
Labels: :sparkles: feature

#159 [MODIFY] 멤버 탈퇴 시 관련 데이터 삭제
  src/main/java/healeat/server/service/UnlinkService.java
Labels: 🔧modify

#164 검색 기록 - 질의어 타입 저장 구현
  src/main/java/healeat/server/converter/SearchPageConverter.java
  src/main/java/healeat/server/service/CategoryFeatureService.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/SearchPageService.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/RecentSearchResponseDto.java
  src/main/java/healeat/server/web/dto/SearchPageRequestDto.java
Labels: :sparkles: feature

#169 가게 단건 조회 구현 - 카카오 데이터, 힐릿 데이터 핸들링 및 로직 정립
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/search/QItemDaumImage.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/Term.java
  src/main/java/healeat/server/domain/search/ItemDaumImage.java
  src/main/java/healeat/server/domain/search/SearchResult.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/repository/BookmarkRepository.java
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepository.java
  src/main/java/healeat/server/repository/StoreRepository.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/DaumImageService.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/ReviewResponseDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
  src/main/java/healeat/server/web/dto/api_response/DaumImageResponseDto.java
Labels: :sparkles: feature

#172 hotfix for workflow
  .github/workflows/dev_deploy.yml
Labels: FIX

#175 가게 홈에 TotalStatDto 추가, path variable인 storeId 대부분을 placeId 로 변경(직관화)
  src/main/java/healeat/server/converter/SearchPageConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/RecentSearchResponseDto.java
  src/main/java/healeat/server/web/dto/ReviewResponseDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :recycle: refactor

#177 #176 [MODIFY] Review 조회 서비스 메서드 일단 ReviewService로 이동, Store 비즈니스 로직 s…
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepository.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCusotm.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/StoreController.java
Labels: 🔧modify

#183 마이페이지 리뷰 조회 로직 수정, 리뷰 이미지 조회 API 구현
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/java/healeat/server/converter/ReviewConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/enums/SortBy.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepository.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCusotm.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepositoryCustomImpl.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/controller/authController/AppleAuthController.java
  src/main/java/healeat/server/web/controller/authController/KakaoUnlinkController.java
  src/main/java/healeat/server/web/controller/authController/NaverUnlinkController.java
  src/main/java/healeat/server/web/controller/authController/SocialLoginController.java
  src/main/java/healeat/server/web/dto/ReviewResponseDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
Labels: :sparkles: feature, 🔧modify

#187 검색 기록 - 가게 타입 저장 구현
  src/main/java/healeat/server/converter/SearchPageConverter.java
  src/main/java/healeat/server/repository/RecentSearchRepository.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/dto/RecentSearchResponseDto.java
Labels: :sparkles: feature

#188 #154 [FEAT] 가게 리뷰 이미지 조회를 전부로 변경, 리뷰 조회 - 페이징/정렬/필터링 완료
  src/main/java/healeat/server/domain/common/BaseEntity.java
  src/main/java/healeat/server/repository/ReviewImageRepository.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepositoryCustomImpl.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/controller/TermController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
Labels: :sparkles: feature

#191 서버에서 Daum 이미지 맡는 것으로 기능 수정
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/search/QItemDaumImage.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/domain/search/ItemDaumImage.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/repository/ReviewImageRepository.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/DaumImageService.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/ReviewResponseDto.java
  src/main/java/healeat/server/web/dto/StoreResponseDto.java
Labels: 🔧modify

#195 리뷰 작성 API 기능 이해 및 해결, 관련 없는 이미지 핸들링을 위한 StoreThumbnail 도메인 구현
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QStoreThumbnail.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/java/healeat/server/converter/ReviewConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/StoreThumbnail.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/StoreThumbnailRepository.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/AnswerRequestDto.java
  src/main/java/healeat/server/web/dto/AppleAuthRequest.java
  src/main/java/healeat/server/web/dto/MemberDiseaseRequestDto.java
  src/main/java/healeat/server/web/dto/ProfileImageRequestDto.java
  src/main/java/healeat/server/web/dto/ReviewRequestDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResponseDto.java
  src/main/java/healeat/server/web/dto/api_response/DaumImageResponseDto.java
Labels: :sparkles: feature, 🔧modify

#201 avgX, avgY 구현, maxDistance 구현, 리뷰/검색기록 자잘 수정
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/domain/search/SearchResult.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/dto/StoreResponseDto.java
  src/main/java/healeat/server/web/dto/api_response/KakaoPlaceResponseDto.java
Labels: :sparkles: feature, 🔧modify

#221 rect 적용: /search
  src/main/generated/healeat/server/domain/QDisease.java
  src/main/generated/healeat/server/domain/QFoodCategory.java
  src/main/generated/healeat/server/domain/QFoodFeature.java
  src/main/generated/healeat/server/domain/QHealthPlan.java
  src/main/generated/healeat/server/domain/QHealthPlanImage.java
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/generated/healeat/server/domain/QReviewImage.java
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QStoreThumbnail.java
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/generated/healeat/server/domain/common/QBaseEntity.java
  src/main/generated/healeat/server/domain/mapping/QBookmark.java
  src/main/generated/healeat/server/domain/mapping/QFeatCategoryMap.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/generated/healeat/server/domain/mapping/QMemberTerm.java
  src/main/generated/healeat/server/domain/mapping/QRecentSearch.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/config/CacheConfig.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
Labels: 🔧modify

#223 마이페이지, 검색(/search/map-rect) 리팩토링
  src/main/generated/healeat/server/domain/QDisease.java
  src/main/generated/healeat/server/domain/QFoodCategory.java
  src/main/generated/healeat/server/domain/QFoodFeature.java
  src/main/generated/healeat/server/domain/QHealthPlan.java
  src/main/generated/healeat/server/domain/QHealthPlanImage.java
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/generated/healeat/server/domain/QReviewImage.java
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QStoreThumbnail.java
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/generated/healeat/server/domain/common/QBaseEntity.java
  src/main/generated/healeat/server/domain/mapping/QBookmark.java
  src/main/generated/healeat/server/domain/mapping/QFeatCategoryMap.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/generated/healeat/server/domain/mapping/QMemberTerm.java
  src/main/generated/healeat/server/domain/mapping/QRecentSearch.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/repository/MemberDiseaseRepository.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/validation/validator/CheckSizeSumValidator.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
Labels: 🔧modify

#224 #222 [MERGE] 머지 해결
  src/main/java/healeat/server/repository/MemberDiseaseRepository.java
Labels: FIX

#226 HealthPlan 도메인 리팩토링
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/converter/HealthPlanConverter.java
  src/main/java/healeat/server/domain/HealthPlan.java
  src/main/java/healeat/server/domain/HealthPlanImage.java
  src/main/java/healeat/server/repository/HealthPlanRepository.java
  src/main/java/healeat/server/service/HealthPlanService.java
  src/main/java/healeat/server/service/ReviewService.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/ImageController.java
  src/main/java/healeat/server/web/controller/InfoController.java
  src/main/java/healeat/server/web/dto/HealthPlanRequestDto.java
Labels: :recycle: refactor

#228 리뷰 필터 and 로 잘못 쓰여진 부분 or 조건으로 수정 + PATCH /{planId}/memo RequestBody 이슈
  src/main/java/healeat/server/converter/ReviewConverter.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepositoryCustomImpl.java
  src/main/java/healeat/server/service/HealthPlanService.java
  src/main/java/healeat/server/service/authService/AppleAuthService.java
  src/main/java/healeat/server/service/authService/AppleTokenService.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/ImageController.java
  src/main/java/healeat/server/web/controller/authController/AppleAuthController.java
  src/main/java/healeat/server/web/controller/authController/KakaoUnlinkController.java
  src/main/java/healeat/server/web/controller/authController/NaverUnlinkController.java
  src/main/java/healeat/server/web/dto/HealInfoResponseDto.java
  src/main/java/healeat/server/web/dto/HealthPlanRequestDto.java
  src/main/java/healeat/server/web/dto/ImageResponseDto.java
  src/main/java/healeat/server/web/dto/authDto/AppleAuthRequest.java
  src/main/java/healeat/server/web/dto/authDto/AppleTokenResponse.java
  src/main/java/healeat/server/web/dto/authDto/AppleUnlinkRequest.java
  src/main/java/healeat/server/web/dto/authDto/UnlinkResponseDto.java
Labels: 🔧modify

#238 프론트 요구사항: placeId 응답 String 타입으로 변경
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/web/dto/ReviewRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResponseDto.java
Labels: 🔧modify

#242 멤버 도메인 수정: 회원 탈퇴 중심
  src/main/generated/healeat/server/domain/QMember.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/BookmarkRepository.java
  src/main/java/healeat/server/repository/ReviewRepository/ReviewRepository.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/authService/UnlinkService.java
  src/main/java/healeat/server/web/controller/authController/KakaoUnlinkController.java
  src/main/java/healeat/server/web/controller/authController/NaverUnlinkController.java
Labels: 🔧modify

#249 [Modify] 로그아웃 수정, 가게 수정
  build.gradle
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/service/authService/LogoutService.java
  src/main/java/healeat/server/user/JwtAuthenticationFilter.java
  src/main/java/healeat/server/web/controller/authController/AppleAuthController.java
  src/main/java/healeat/server/web/controller/authController/AuthController.java
  src/main/java/healeat/server/web/dto/StoreResponseDto.java
Labels: 🔧modify

#251 로그인 안 한 사용자의 접근 여부 고려
  src/main/java/healeat/server/converter/SearchPageConverter.java
  src/main/java/healeat/server/service/RecentSearchService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
Labels: :sparkles: feature

#253 리뷰 이미지 정렬 수정
  src/main/java/healeat/server/repository/ReviewImageRepository.java
  src/main/java/healeat/server/service/ReviewService.java
Labels: 🔧modify

#257 #256 [MODIFY] QueryDSL: store의 id -> kakaoPlaceId
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepositoryCustomImpl.java
  src/main/java/healeat/server/service/MemberService.java
Labels: 🔧modify

#258 #256 [MODIFY] 홈에서도 임시로 전체 별점 순 정렬
  src/main/java/healeat/server/service/StoreCommandServiceImpl.java
Labels: 🔧modify
