Repository HealEat/Backend, pull requests merged in 2025-01, with the labels that each got.

#10 #9 [FEAT][ADD] Store, Review 도메인 비즈니스 로직, StoreResponseDto 작성, DietAn...
  build.gradle
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/ReviewHandler.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/enums/DietAns.java
  src/main/java/healeat/server/domain/mapping/MemberDisease.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :sparkles: feature

#12 #11 [MODIFY] 여러가지 도메인 수정
  src/main/java/healeat/server/domain/FoodToAvoid.java
  src/main/java/healeat/server/domain/HealthPlan.java
  src/main/java/healeat/server/domain/KeywordCategory.java
  src/main/java/healeat/server/domain/MealNeeded.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemoImage.java
  src/main/java/healeat/server/domain/NutrientNeeded.java
  src/main/java/healeat/server/domain/ReviewImage.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/Term.java
  src/main/java/healeat/server/domain/enums/DietAns.java
  src/main/java/healeat/server/domain/enums/Duration.java
  src/main/java/healeat/server/domain/enums/FoodToAvoidAns.java
  src/main/java/healeat/server/domain/enums/Vegeterian.java
  src/main/java/healeat/server/domain/mapping/MemberDisease.java
  src/main/java/healeat/server/domain/mapping/MemberFoodToAvoid.java
  src/main/java/healeat/server/domain/mapping/MemberMealNeeded.java
  src/main/java/healeat/server/domain/mapping/MemberNutrientNeeded.java
  src/main/java/healeat/server/domain/mapping/MemberTerm.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/domain/mapping/StoreKeyword.java
Labels: :recycle: refactor, 🔧modify, 🔥remove

#14 #11 [ADD] HealthIssue 관련 엔티티 추가
  src/main/java/healeat/server/domain/HealthIssue.java
  src/main/java/healeat/server/domain/mapping/MemberHealthIssue.java
Labels: ➕add

#19 #11 [FEAT] Member, Review의 current_health_goal 필드 추가, Store의 건강 목표 별 …
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/mapping/Review.java
Labels: :sparkles: feature

#16 #6 [Feature] Spring Security 설정
  build.gradle
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/resources/application.yml.template
Labels: :sparkles: feature

#21 [REMOVE] 단순 더미 삭제
  src/main/java/healeat/server/domain/MemberHealthInfo.java
Labels: 🔥remove

#23 #22 [CORRECT] 머지 결과 Question 클래스가 두 개여서 하나 지움, MemberHealthInfoQuesti…
  build.gradle
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/domain/HealthInfoAnswer.java
  src/main/java/healeat/server/domain/HealthInfoQuestion.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemberHealQuestion.java
  src/main/java/healeat/server/repository/HealthInfoAnswerRepository.java
  src/main/java/healeat/server/repository/MemberHealQuestionRepository.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/MemberHealthInfoController.java
Labels: :recycle: refactor, ✏️correct

#25 #24 [Modify] 회원 건강 정보 controller 수정, converter 생성
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/MemberHealthInfoHandler.java
  src/main/java/healeat/server/converter/MemberHealthInfoConverter.java
  src/main/java/healeat/server/repository/HealthInfoAnswerRepository.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/web/controller/MemberHealthInfoController.java
  src/main/java/healeat/server/web/dto/AnswerRequestDto.java
  src/main/java/healeat/server/web/dto/AnswerResponseDto.java
  src/main/java/healeat/server/web/dto/QuestionResponseDto.java
  src/test/java/healeat/server/MemberHealthInfoConverterTest.java
Labels: 🔧modify

#27 #26 [MODIFY] MemberHealthInfo- purpose 관련 도메인 수정
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/enums/Purpose.java
  src/main/java/healeat/server/domain/mapping/MemberPurpose.java
  src/main/java/healeat/server/domain/mapping/PurposeAnswer.java
Labels: 🔧modify

#28 [FEAT] [TEST] 리뷰 조회, 외부 API 테스트
  build.gradle
  src/main/java/healeat/server/HealEatServerApplication.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/StoreHandler.java
  src/main/java/healeat/server/config/FeignConfig.java
  src/main/java/healeat/server/converter/ReviewConverter.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemberPurpose.java
  src/main/java/healeat/server/domain/PurposeAnswer.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/enums/Purpose.java
  src/main/java/healeat/server/domain/enums/Vegetarian.java
  src/main/java/healeat/server/domain/mapping/MemberDisease.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/ReviewRepository.java
  src/main/java/healeat/server/repository/StoreRepository.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/StoreQueryService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/validation/annotation/CheckPage.java
  src/main/java/healeat/server/validation/validator/CheckPageValidator.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/DaumImageResponseDto.java
  src/main/java/healeat/server/web/dto/KakaoPlaceResponseDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
  src/test/java/healeat/server/service/StoreApiClientTest.java
Labels: :sparkles: feature, 🧪 test

#31 #30 [CI] ci/cd 스크립트 작성
  .github/workflows/dev_deploy.yml
  src/main/java/healeat/server/apiPayload/exception/handler/MemberHandler.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/enums/Answer.java
  src/main/java/healeat/server/domain/enums/DietAns.java
  src/main/java/healeat/server/domain/enums/Vegetarian.java
  src/main/java/healeat/server/repository/ReviewRepository.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/MemberHealthInfoController.java
  src/main/java/healeat/server/web/dto/AnswerResponseDto.java
Labels: :sparkles: feature, 👷ci

#33 #30 [CI] 배포 및 테스트
  .github/workflows/dev_deploy.yml
  src/main/java/healeat/server/domain/Member.java
Labels: :sparkles: feature, 👷ci

#34 #30 [CI] ci/cd 배포 및 테스트
  .gitignore
  src/main/resources/application.yml.template
Labels: :sparkles: feature, 👷ci

#38 #30 [FIX] dev_deploy.yml actions/upload-artifact 최신버전 v4로 적용
  .github/workflows/dev_deploy.yml
Labels: :recycle: refactor, 👷ci

#39 #30 [FIX] actions/download-artifact도 v4로 최신화
  .github/workflows/dev_deploy.yml
Labels: :recycle: refactor, 👷ci

#37 #29 [MODIFY], [ADD] questionId 타입 수정, 질병 api 추가
  src/main/java/healeat/server/config/DiseaseFeignConfig.java
  src/main/java/healeat/server/converter/MemberHealthInfoConverter.java
  src/main/java/healeat/server/domain/MemberHealQuestion.java
  src/main/java/healeat/server/domain/enums/Diet.java
  src/main/java/healeat/server/domain/enums/Veget.java
  src/main/java/healeat/server/repository/MemberHealQuestionRepository.java
  src/main/java/healeat/server/service/DiseaseFeignClient.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/MemberService.java
  src/main/java/healeat/server/web/controller/MemberHealthInfoController.java
  src/main/java/healeat/server/web/dto/AnswerRequestDto.java
  src/main/java/healeat/server/web/dto/AnswerResponseDto.java
  src/main/java/healeat/server/web/dto/DiseaseApiResponse.java
  src/main/java/healeat/server/web/dto/QuestionResponseDto.java
Labels: ➕add, 🔧modify

#46 #44 [FEAT] Member에 건강 정보 기반 결과 저장, RecentSearch 테이블 수정
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/enums/SearchType.java
  src/main/java/healeat/server/domain/mapping/RecentSearch.java
  src/main/java/healeat/server/service/FoodRecommendation.java
Labels: :sparkles: feature

#51 #51 [Feat] 일반 검색 로직 스웨거 테스트 서비스
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/healeat/server/config/FeignConfig.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/FoodCategory.java
  src/main/java/healeat/server/domain/FoodFeature.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository.java
  src/main/java/healeat/server/repository/FoodCategoryRepository.java
  src/main/java/healeat/server/repository/FoodFeatureRepository.java
  src/main/java/healeat/server/repository/HealthInfoAnswerRepository.java
  src/main/java/healeat/server/repository/HealthPlanRepository.java
  src/main/java/healeat/server/repository/MemberHealQuestionRepository.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreCommandService.java
  src/main/java/healeat/server/service/StoreQueryService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/validation/annotation/CheckSizeSum.java
  src/main/java/healeat/server/validation/validator/CheckSizeSumValidator.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/KakaoPlaceResponseDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/TestResponseDto.java
  src/test/java/healeat/server/FeatCategoryMapTest.java
  src/test/java/healeat/server/service/SearchTest.java
  src/test/java/healeat/server/service/StoreApiClientTest.java
Labels: :sparkles: feature

#54 #51 [MODIFY][FEAT] 일반 검색 로직 수정
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
Labels: :sparkles: feature, 🔧modify

#53 [FEAT] #49 MemberProfile설정 api 구현
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/repository/MemberRepository.java
  src/main/java/healeat/server/service/MemberService.java
  src/main/java/healeat/server/web/controller/MemberController.java
  src/main/java/healeat/server/web/dto/MemberProfileRequestDto.java
  src/main/java/healeat/server/web/dto/MemberProfileResponseDto.java
Labels: :sparkles: feature

#58 [FEAT] 카카오 데이터와 힐릿 Store Response 매핑하기
  src/main/java/healeat/server/config/FeignConfig.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository.java
  src/main/java/healeat/server/repository/FoodFeatureRepository.java
  src/main/java/healeat/server/service/CustomPagination.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/dto/KakaoPlaceResponseDto.java
  src/main/java/healeat/server/web/dto/KakaoXYResponseDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :sparkles: feature

#61 일반 검색 서비스 구현 완료(캐싱 제외), 시큐리티 코드 수정, 깃 yml 수정
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository.java
  src/main/java/healeat/server/repository/FoodCategoryRepository.java
  src/main/java/healeat/server/repository/MemberRepository.java
  src/main/java/healeat/server/repository/RecentSearchRepository.java
  src/main/java/healeat/server/service/CustomOAuth2UserService.java
  src/main/java/healeat/server/service/CustomPagination.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/test/java/healeat/server/MemberHealthInfoConverterTest.java
Labels: :recycle: refactor, FIX

#70 #68 [REFACTOR] 충돌 해결
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :recycle: refactor

#73 엔드포인트 큰 틀 확정, 리팩토링
  src/main/java/healeat/server/config/SecurityConfig.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/InfoController.java
  src/main/java/healeat/server/web/controller/MemberController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
Labels: :recycle: refactor

#77 [FEAT] #62-bookmark 기능 구현
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/repository/BookmarkRepository.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/BookmarkController.java
Labels: :sparkles: feature

#95 info 도메인 : 건강 정보 답변 저장/수정 구현
  src/main/generated/healeat/server/domain/QHealthInfoAnswer.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/apiPayload/exception/handler/HealthInfoHandler.java
  src/main/java/healeat/server/config/FoodMappingConfig.java
  src/main/java/healeat/server/converter/MemberHealQuestionConverter.java
  src/main/java/healeat/server/converter/MemberHealthInfoConverter.java
  src/main/java/healeat/server/domain/HealthInfoAnswer.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemberHealQuestion.java
  src/main/java/healeat/server/domain/enums/Answer.java
  src/main/java/healeat/server/domain/enums/Diet.java
  src/main/java/healeat/server/domain/enums/Vegetarian.java
  src/main/java/healeat/server/repository/HealthInfoAnswerRepository.java
  src/main/java/healeat/server/repository/MemberHealQuestionRepository.java
  src/main/java/healeat/server/service/FoodRecommendation.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/MemberService.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/search/QueryAnalysisService.java
  src/main/java/healeat/server/web/controller/InfoController.java
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/dto/AnswerRequestDto.java
  src/main/java/healeat/server/web/dto/AnswerResponseDto.java
  src/main/java/healeat/server/web/dto/HealInfoResponseDto.java
  src/main/java/healeat/server/web/dto/MemberProfileResponseDto.java
  src/main/java/healeat/server/web/dto/api_response/DaumImageResponseDto.java
  src/test/java/healeat/server/MemberHealthInfoConverterTest.java
Labels: :recycle: refactor, :sparkles: feature

#97 멤버 주입, 베지테리언 및 다이어트 선택 수정 API 구현
  src/main/java/healeat/server/config/TestSecurityConfig.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemberHealQuestion.java
  src/main/java/healeat/server/service/HealthPlanService.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/MemberService.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/MyPageController.java
Labels: :sparkles: feature

#99 TestSecurityConfig hotfix
  src/main/java/healeat/server/config/TestSecurityConfig.java
  src/test/java/healeat/server/HealEatServerApplicationTests.java
Labels: FIX

#102 테스트 환경 롤백, 컨트롤러 단에서 999번 testMember 사용, Info 도메인 서비스 컨버터 분리
  src/main/java/healeat/server/config/FoodMappingConfig.java
  src/main/java/healeat/server/config/TestSecurityConfig.java
  src/main/java/healeat/server/converter/MemberHealQuestionConverter.java
  src/main/java/healeat/server/domain/enums/Diet.java
  src/main/java/healeat/server/domain/enums/Vegetarian.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/FoodRecommendation.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/BookmarkController.java
  src/main/java/healeat/server/web/controller/HealthPlanController.java
  src/main/java/healeat/server/web/controller/HomeController.java
  src/main/java/healeat/server/web/controller/InfoController.java
  src/main/java/healeat/server/web/controller/MyPageController.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/HealInfoResponseDto.java
  src/test/java/healeat/server/HealEatServerApplicationTests.java
Labels: :recycle: refactor

#106 북마크 구현과 검색 로직 연결
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/healeat/server/converter/BookmarkConverter.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/search/SearchResultItem.java
  src/main/java/healeat/server/repository/BookmarkRepository.java
  src/main/java/healeat/server/service/BookmarkService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/web/controller/BookmarkController.java
  src/main/java/healeat/server/web/controller/StoreController.java
  src/main/java/healeat/server/web/dto/BookmarkResponseDto.java
  src/main/java/healeat/server/web/dto/MemberHealthInfoResponseDto.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :sparkles: feature

#110 깃액션 yml 도메인 네임으로 통일, HTTP 메서드 수정
  src/main/java/healeat/server/web/controller/InfoController.java
Labels: :recycle: refactor

#104 [REFACTOR] #103-disease refactoring
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/mapping/MemberDisease.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/repository/MemberDiseaseRepository.java
  src/main/java/healeat/server/repository/ReviewRepository.java
  src/main/java/healeat/server/service/DiseaseService.java
  src/main/java/healeat/server/service/MemberHealthInfoService.java
  src/main/java/healeat/server/service/MemberService.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/web/controller/InfoController.java
Labels: :recycle: refactor

#117 search 기능 간소화에 따른 작업(스프링부트 캐시 적용 전)
  src/main/generated/healeat/server/domain/QDisease.java
  src/main/generated/healeat/server/domain/QFoodCategory.java
  src/main/generated/healeat/server/domain/QFoodFeature.java
  src/main/generated/healeat/server/domain/QHealthPlan.java
  src/main/generated/healeat/server/domain/QHealthPlanImage.java
  src/main/generated/healeat/server/domain/QMember.java
  src/main/generated/healeat/server/domain/QMemberHealQuestion.java
  src/main/generated/healeat/server/domain/QReviewImage.java
  src/main/generated/healeat/server/domain/QStore.java
  src/main/generated/healeat/server/domain/QTerm.java
  src/main/generated/healeat/server/domain/common/QBaseEntity.java
  src/main/generated/healeat/server/domain/mapping/QBookmark.java
  src/main/generated/healeat/server/domain/mapping/QFeatCategoryMap.java
  src/main/generated/healeat/server/domain/mapping/QMemberDisease.java
  src/main/generated/healeat/server/domain/mapping/QMemberTerm.java
  src/main/generated/healeat/server/domain/mapping/QRecentSearch.java
  src/main/generated/healeat/server/domain/mapping/QReview.java
  src/main/generated/healeat/server/domain/search/QSearchResult.java
  src/main/generated/healeat/server/domain/search/QSearchResultItem.java
  src/main/java/healeat/server/HealEatServerApplication.java
  src/main/java/healeat/server/converter/StoreConverter.java
  src/main/java/healeat/server/domain/HealthPlan.java
  src/main/java/healeat/server/domain/Member.java
  src/main/java/healeat/server/domain/MemberHealQuestion.java
  src/main/java/healeat/server/domain/Store.java
  src/main/java/healeat/server/domain/Term.java
  src/main/java/healeat/server/domain/mapping/Review.java
  src/main/java/healeat/server/domain/search/SearchResult.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository/FeatCategoryMapRepositoryCustom.java
  src/main/java/healeat/server/repository/FeatCategoryMapRepository/FeatCategoryMapRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/SearchResultItemRepository/SearchResultItemRepositoryCustomImpl.java
  src/main/java/healeat/server/repository/SearchResultRepository.java
  src/main/java/healeat/server/service/StoreApiClient.java
  src/main/java/healeat/server/service/StoreQueryServiceImpl.java
  src/main/java/healeat/server/service/search/ApiCallCountService.java
  src/main/java/healeat/server/service/search/QueryAnalysisService.java
  src/main/java/healeat/server/service/search/SearchFeatureService.java
  src/main/java/healeat/server/service/search/SearchInfoService.java
  src/main/java/healeat/server/service/search/SearchResultKey.java
  src/main/java/healeat/server/service/search/SearchResultScheduler.java
  src/main/java/healeat/server/service/search/StoreMappingService.java
  src/main/java/healeat/server/service/search/StoreSearchService.java
  src/main/java/healeat/server/web/controller/SearchController.java
  src/main/java/healeat/server/web/dto/StoreRequestDto.java
  src/main/java/healeat/server/web/dto/StoreResonseDto.java
Labels: :sparkles: feature
